=== lectroidmarc/SacTraffic/process_chp-config.dtd
<!ELEMENT config		(jsonpath, dispatch*)>

<!ELEMENT jsonpath		(#PCDATA)>

<!ELEMENT dispatch		(geocode*, twitter*, bitly?)?>
<!ATTLIST dispatch name		CDATA #REQUIRED>

<!ELEMENT geocode		(#PCDATA)>
<!ATTLIST geocode name		CDATA #REQUIRED>
<!ATTLIST geocode apikey	CDATA #REQUIRED>

<!ELEMENT twitter		(#PCDATA)>
<!ATTLIST twitter login		CDATA #REQUIRED>
<!ATTLIST twitter password	CDATA #REQUIRED>

<!ELEMENT bitly			(#PCDATA)>
<!ATTLIST bitly login		CDATA #REQUIRED>
<!ATTLIST bitly apikey		CDATA #REQUIRED>

=== lectroidmarc/SacTraffic/process_chp-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "process_chp-config.dtd">

<config>
	<!-- defaults -->
	<jsonpath>htdocs/json</jsonpath>

	<!-- Sacramento -->
	<dispatch name="STCC-STCC">
		<geocode name="google" apikey="ABQIAAAAlAZP1OSueWm4o6pWOnsJahTWfCw_DNErtpfmuWl6JQkzmGW7WBT9Yucup9PJ4DO-lhEdGj3-tXkTwQ"/>
		<geocode name="yahoo" apikey=".7eSeNXV34FtD2sVFkwjUCKHS_PCGPyud.paQ5Az7xX3zBUFC6DoVsu5E3.1hPowluSe"/>

		<twitter login="sactraffic" password="snowcrash"/>
	</dispatch>

	<!-- Merced -->
	<dispatch name="FRCC-MRCC">
	</dispatch>

	<!-- Fresno -->
	<dispatch name="FRCC-FRCC">
	</dispatch>
</config>
